; skip.scm -- tests that cannot run yet on the chip Scheme, with the reason.
; Read by host.lisp (suite.lisp). Entries:
;   (section "NAME" "reason")   every test in that test-begin section
;   (head "NAME" "reason")      forms whose head, or a nested test, is NAME
;   (match "TEXT" "reason")     forms whose text contains TEXT
;   (nonlatin1 "" "reason")    forms with a character beyond Latin-1
;   (literal "KIND" "reason")   forms with a number literal of KIND: bignum float ratio complex prefix
; Remove an entry when the feature lands; the skip count must only go down.
(head "import" "no libraries: (import ...) not supported")
(head "test-error" "no exceptions: test-error needs raise/guard")
(head "test-values" "no multiple values")
(head "test-numeric-syntax" "no string->number / number->string")
(head "test-precision" "no inexact reals")
(head "test-read-error" "no read procedure or ports")
(head "test-write-syntax" "no ports: write to string")
(head "define-syntax" "no define-syntax / syntax-rules")
(head "let-syntax" "no let-syntax")
(head "define-record-type" "no records")
(section "4.3 Macros" "no define-syntax / syntax-rules")
(section "6.11 Exceptions" "no exceptions")
(section "6.12 Environments and evaluation" "no eval / environments")
(section "6.13 Input and output" "no ports beyond the console")
(section "6.14 System interface" "no system interface")
(section "Read syntax" "no read procedure or ports")
(section "Numeric syntax" "no string->number")
(match "let*-values" "no multiple values")
(match "let-values" "no multiple values")
(match "call-with-values" "no multiple values")
(match "(values" "no multiple values")
(match "call-with-current-continuation" "no call/cc")
(match "call/cc" "no call/cc")
(match "dynamic-wind" "no dynamic-wind")
(match "delay" "no delay/force")
(match "make-promise" "no delay/force")
(match "parameterize" "no parameters")
(match "make-parameter" "no parameters")
(match "`" "no quasiquote")
(match "case-lambda" "no case-lambda")
(match "string->number" "no string->number")
(match "number->string" "no number->string")
(match "guard" "no exceptions")
(match "error-object" "no exceptions")
(match "raise" "no exceptions")
(match "with-exception-handler" "no exceptions")
(match "exact-integer-sqrt" "no multiple values")
(match "floor/" "no multiple values")
(match "truncate/" "no multiple values")
(literal "bignum" "no bignums: fixnums are 31-bit, beyond that is an overflow error")
(literal "complex" "no complex numbers")
(literal "prefix" "no #e #i #x #b #o #d number prefixes")
(nonlatin1 "" "no Unicode: characters and strings are bytes; the serial link is Latin-1")
