; prelude.scm -- R7RS-small procedures written in the chip Scheme itself.
; host.lisp sends this file to the chip REPL one line at a time: keep one form per line.
(define (not x) (if x #f #t))
(define (caar x) (car (car x)))
(define (cadr x) (car (cdr x)))
(define (cdar x) (cdr (car x)))
(define (cddr x) (cdr (cdr x)))
(define (caddr x) (car (cddr x)))
(define (list . xs) xs)
(define (length l) (let loop ((l l) (n 0)) (if (pair? l) (loop (cdr l) (+ n 1)) n)))
(define (reverse l) (let loop ((l l) (acc '())) (if (pair? l) (loop (cdr l) (cons (car l) acc)) acc)))
(define (append2 a b) (if (pair? a) (cons (car a) (append2 (cdr a) b)) b))
(define (append . ls) (cond ((null? ls) '()) ((null? (cdr ls)) (car ls)) (else (append2 (car ls) (apply append (cdr ls))))))
(define (list-tail l k) (if (= k 0) l (list-tail (cdr l) (- k 1))))
(define (list-ref l k) (car (list-tail l k)))
(define (map1 f l) (if (pair? l) (cons (f (car l)) (map1 f (cdr l))) '()))
(define (any-null? ls) (cond ((null? ls) #f) ((null? (car ls)) #t) (else (any-null? (cdr ls)))))
(define (map f . ls) (if (null? (cdr ls)) (map1 f (car ls)) (if (any-null? ls) '() (cons (apply f (map1 car ls)) (apply map f (map1 cdr ls))))))
(define (for-each f . ls) (if (any-null? ls) #t (begin (apply f (map1 car ls)) (apply for-each f (map1 cdr ls)))))
(define (equal? a b) (cond ((and (pair? a) (pair? b)) (and (equal? (car a) (car b)) (equal? (cdr a) (cdr b)))) ((and (string? a) (string? b)) (= 0 (%string-compare a b))) ((and (vector? a) (vector? b)) (equal? (vector->list a) (vector->list b))) ((and (bytevector? a) (bytevector? b)) (equal? (%bytevector->list a) (%bytevector->list b))) (else (eqv? a b))))
(define (mem= same? x l) (cond ((null? l) #f) ((same? x (car l)) l) (else (mem= same? x (cdr l)))))
(define (memq x l) (mem= eq? x l))
(define (memv x l) (mem= eqv? x l))
(define (member x l) (mem= equal? x l))
(define (ass= same? x l) (cond ((null? l) #f) ((same? x (car (car l))) (car l)) (else (ass= same? x (cdr l)))))
(define (assq x l) (ass= eq? x l))
(define (assv x l) (ass= eqv? x l))
(define (assoc x l) (ass= equal? x l))
(define (zero? n) (= n 0))
(define (positive? n) (> n 0))
(define (negative? n) (< n 0))
(define (odd? n) (not (= 0 (remainder n 2))))
(define (even? n) (= 0 (remainder n 2)))
(define (abs n) (if (< n 0) (- n) n))
(define (max x . r) (let loop ((m x) (r r) (i (inexact? x))) (if (null? r) (if i (inexact m) m) (loop (if (> (car r) m) (car r) m) (cdr r) (or i (inexact? (car r)))))))
(define (min x . r) (let loop ((m x) (r r) (i (inexact? x))) (if (null? r) (if i (inexact m) m) (loop (if (< (car r) m) (car r) m) (cdr r) (or i (inexact? (car r)))))))
(define (numerator q) (if (exact? q) (%numerator q) (inexact (%numerator (exact q)))))
(define (denominator q) (if (exact? q) (%denominator q) (inexact (%denominator (exact q)))))
(define (exact->inexact z) (inexact z))
(define (inexact->exact z) (exact z))
(define (finite? z) (not (or (nan? z) (infinite? z))))
(define (gcd . ns) (if (null? ns) 0 (let loop ((a (abs (car ns))) (r (cdr ns))) (if (null? r) a (loop (let g ((a a) (b (abs (car r)))) (if (= b 0) a (g b (remainder a b)))) (cdr r))))))
(define (lcm . ns) (if (null? ns) 1 (let loop ((a (abs (car ns))) (r (cdr ns))) (if (null? r) a (loop (if (= a 0) 0 (quotient (abs (* a (car r))) (gcd a (car r)))) (cdr r))))))
(define (square n) (* n n))
(define (boolean=? a b) (eq? a b))
(define (symbol=? a b) (eq? a b))
(define (list? l) (let loop ((slow l) (fast l)) (cond ((null? fast) #t) ((not (pair? fast)) #f) ((null? (cdr fast)) #t) ((not (pair? (cdr fast))) #f) (else (let ((fast (cddr fast)) (slow (cdr slow))) (if (eq? fast slow) #f (loop slow fast)))))))
(define (list-copy l) (if (pair? l) (cons (car l) (list-copy (cdr l))) l))
(define (make-list k . fill) (let loop ((k k) (acc '())) (if (= k 0) acc (loop (- k 1) (cons (if (null? fill) #f (car fill)) acc)))))
(define (string->list s . r) (%string->list s (if (pair? r) (car r) 0) (if (and (pair? r) (pair? (cdr r))) (cadr r) (string-length s))))
(define (vector->list v . r) (%vector->list v (if (pair? r) (car r) 0) (if (and (pair? r) (pair? (cdr r))) (cadr r) (vector-length v))))
(define (substring s start end) (%substring s start end))
(define (string-copy s . r) (%substring s (if (pair? r) (car r) 0) (if (and (pair? r) (pair? (cdr r))) (cadr r) (string-length s))))
(define (string-append . ss) (let loop ((acc "") (ss ss)) (if (null? ss) acc (loop (%string-append2 acc (car ss)) (cdr ss)))))
(define (string . cs) (list->string cs))
(define (%chain cmp ok? xs) (let loop ((xs xs)) (cond ((null? (cdr xs)) #t) ((ok? (cmp (car xs) (cadr xs))) (loop (cdr xs))) (else #f))))
(define (string=? . ss) (%chain %string-compare zero? ss))
(define (string<? . ss) (%chain %string-compare negative? ss))
(define (string>? . ss) (%chain %string-compare positive? ss))
(define (string<=? . ss) (%chain %string-compare (lambda (n) (<= n 0)) ss))
(define (string>=? . ss) (%chain %string-compare (lambda (n) (>= n 0)) ss))
(define (%ccmp a b) (- (char->integer a) (char->integer b)))
(define (char=? . cs) (%chain %ccmp zero? cs))
(define (char<? . cs) (%chain %ccmp negative? cs))
(define (char>? . cs) (%chain %ccmp positive? cs))
(define (char<=? . cs) (%chain %ccmp (lambda (n) (<= n 0)) cs))
(define (char>=? . cs) (%chain %ccmp (lambda (n) (>= n 0)) cs))
(define (char-upper-case? c) (let ((n (char->integer c))) (and (>= n 65) (<= n 90))))
(define (char-lower-case? c) (let ((n (char->integer c))) (and (>= n 97) (<= n 122))))
(define (char-alphabetic? c) (or (char-upper-case? c) (char-lower-case? c)))
(define (char-numeric? c) (let ((n (char->integer c))) (and (>= n 48) (<= n 57))))
(define (char-whitespace? c) (if (memv (char->integer c) '(32 9 10 12 13)) #t #f))
(define (char-upcase c) (if (char-lower-case? c) (integer->char (- (char->integer c) 32)) c))
(define (char-downcase c) (if (char-upper-case? c) (integer->char (+ (char->integer c) 32)) c))
(define (char-foldcase c) (char-downcase c))
(define (digit-value c) (if (char-numeric? c) (- (char->integer c) 48) #f))
(define (vector . xs) (list->vector xs))
(define (vector-fill! v x . r) (let loop ((i (if (pair? r) (car r) 0))) (if (< i (if (and (pair? r) (pair? (cdr r))) (cadr r) (vector-length v))) (begin (vector-set! v i x) (loop (+ i 1))))))
(define (vector-copy v . r) (list->vector (apply vector->list v r)))
(define (vector-append . vs) (list->vector (apply append (map vector->list vs))))
(define (vector-map f . vs) (list->vector (apply map f (map vector->list vs))))
(define (vector-for-each f . vs) (apply for-each f (map vector->list vs)))
(define (string-map f . ss) (list->string (apply map f (map string->list ss))))
(define (string-for-each f . ss) (apply for-each f (map string->list ss)))
(define (vector->string v . r) (list->string (apply vector->list v r)))
(define (string->vector s . r) (list->vector (apply string->list s r)))
(define (bytevector . bs) (list->bytevector bs))
(define (bytevector->list b) (%bytevector->list b))
(define (bytevector-copy b . r) (let ((l (%bytevector->list b))) (list->bytevector (list-head (list-tail l (if (pair? r) (car r) 0)) (- (if (and (pair? r) (pair? (cdr r))) (cadr r) (length l)) (if (pair? r) (car r) 0))))))
(define (list-head l k) (if (= k 0) '() (cons (car l) (list-head (cdr l) (- k 1)))))
(define (bytevector-append . bs) (list->bytevector (apply append (map %bytevector->list bs))))
(define (utf8->string b) (list->string (map integer->char (%bytevector->list b))))
(define (string->utf8 s) (list->bytevector (map char->integer (string->list s))))
(define (floor x) (cond ((exact-integer? x) x) ((exact? x) (let ((n (numerator x)) (d (denominator x))) (if (>= n 0) (quotient n d) (- (quotient (+ (- n) d -1) d))))) (else (let ((t (%ftruncate x))) (if (> t x) (- t 1) t)))))
(define (ceiling x) (- (floor (- x))))
(define (truncate x) (cond ((exact-integer? x) x) ((exact? x) (quotient (numerator x) (denominator x))) (else (%ftruncate x))))
(define (round x) (let* ((f (floor x)) (diff (- x f))) (cond ((< diff 1/2) f) ((> diff 1/2) (+ f 1)) ((even? (exact f)) f) (else (+ f 1)))))
(define (%isqrt n) (if (< n 2) n (let loop ((x n)) (let ((y (quotient (+ x (quotient n x)) 2))) (if (>= y x) x (loop y))))))
(define (sqrt x) (cond ((and (exact-integer? x) (>= x 0)) (let ((s (%isqrt x))) (if (= (* s s) x) s (%fsqrt x)))) ((and (exact? x) (>= x 0)) (let ((a (sqrt (numerator x))) (b (sqrt (denominator x)))) (if (and (exact? a) (exact? b)) (/ a b) (%fsqrt x)))) (else (%fsqrt x))))
(define (exact-integer-sqrt n) (let ((s (%isqrt n))) (list s (- n (* s s)))))
(define (%cicmp a b) (- (char->integer (char-foldcase a)) (char->integer (char-foldcase b))))
(define (char-ci=? . cs) (%chain %cicmp zero? cs))
(define (char-ci<? . cs) (%chain %cicmp negative? cs))
(define (char-ci>? . cs) (%chain %cicmp positive? cs))
(define (char-ci<=? . cs) (%chain %cicmp (lambda (n) (<= n 0)) cs))
(define (char-ci>=? . cs) (%chain %cicmp (lambda (n) (>= n 0)) cs))
; ---- item 4: syntax, control and data abstractions, written as procedural macros ----
; A macro is a box made by %macro around a procedure from the whole form to its expansion;
; eval expands it before evaluating. syntax-rules builds such a procedure (not hygienic).
(define (cadddr x) (car (cdddr x)))
(define (cdddr x) (cdr (cddr x)))
(define (cddddr x) (cdr (cdddr x)))

(define (%qq x depth)
  (cond ((vector? x) (list 'list->vector (%qq (vector->list x) depth)))
        ((not (pair? x)) (list 'quote x))
        ((eq? (car x) 'unquote)
         (if (= depth 0) (cadr x) (list 'list ''unquote (%qq (cadr x) (- depth 1)))))
        ((eq? (car x) 'quasiquote) (list 'list ''quasiquote (%qq (cadr x) (+ depth 1))))
        ((and (pair? (car x)) (eq? (caar x) 'unquote-splicing) (= depth 0))
         (list 'append (cadr (car x)) (%qq (cdr x) depth)))
        (else (list 'cons (%qq (car x) depth) (%qq (cdr x) depth)))))
(define-syntax quasiquote (%macro (lambda (f) (%qq (cadr f) 0))))

; syntax-rules: match patterns (with ellipsis, literals, _) and fill templates.
(define (%sr-vars pat lits ell)
  (cond ((symbol? pat) (if (or (memq pat lits) (eq? pat ell) (eq? pat '_)) '() (list pat)))
        ((pair? pat) (append (%sr-vars (car pat) lits ell) (%sr-vars (cdr pat) lits ell)))
        ((vector? pat) (%sr-vars (vector->list pat) lits ell))
        (else '())))
(define (%sr-match pat form lits ell b)
  (cond ((not b) #f)
        ((symbol? pat)
         (cond ((memq pat lits) (if (eq? pat form) b #f))
               ((eq? pat '_) b)
               (else (cons (cons pat form) b))))
        ((and (pair? pat) (pair? (cdr pat)) (eq? (cadr pat) ell))
         (let* ((tail (cddr pat)) (tn (let loop ((t tail) (n 0)) (if (pair? t) (loop (cdr t) (+ n 1)) n)))
                (fn (let loop ((f form) (n 0)) (if (pair? f) (loop (cdr f) (+ n 1)) n))))
           (if (< fn tn) #f
               (let loop ((f form) (k (- fn tn)) (ms '()))
                 (if (> k 0)
                     (let ((m (%sr-match (car pat) (car f) lits ell (list (cons '%ok #t)))))
                       (if m (loop (cdr f) (- k 1) (cons m ms)) #f))
                     (let ((ms (reverse ms)))
                       (%sr-match tail f lits ell
                                  (append (map (lambda (v) (cons v (cons '%seq (map (lambda (m) (cdr (assq v m))) ms))))
                                               (%sr-vars (car pat) lits ell))
                                          b))))))))
        ((pair? pat) (and (pair? form) (%sr-match (cdr pat) (cdr form) lits ell (%sr-match (car pat) (car form) lits ell b))))
        ((null? pat) (if (null? form) b #f))
        ((vector? pat) (and (vector? form) (%sr-match (vector->list pat) (vector->list form) lits ell b)))
        (else (if (equal? pat form) b #f))))
(define (%sr-seq? v) (and (pair? v) (eq? (car v) '%seq)))
(define (%sr-expand t b ell)
  (cond ((symbol? t) (let ((p (assq t b))) (if p (cdr p) t)))
        ((and (pair? t) (eq? (car t) ell) (pair? (cdr t))) (%sr-expand (cadr t) '() '%no-ellipsis))
        ((and (pair? t) (pair? (cdr t)) (eq? (cadr t) ell))
         (let* ((vars (filter (lambda (v) (let ((p (assq v b))) (and p (%sr-seq? (cdr p))))) (%sr-vars (car t) '() ell)))
                (n (if (null? vars) 0 (length (cddr (assq (car vars) b))))))
           (let loop ((i (- n 1)) (acc (%sr-expand (cddr t) b ell)))
             (if (< i 0) acc
                 (loop (- i 1)
                       (cons (%sr-expand (car t) (append (map (lambda (v) (cons v (list-ref (cddr (assq v b)) i))) vars) b) ell) acc))))))
        ((pair? t) (cons (%sr-expand (car t) b ell) (%sr-expand (cdr t) b ell)))
        ((vector? t) (list->vector (%sr-expand (vector->list t) b ell)))
        (else t)))
(define (filter ok? l) (cond ((null? l) '()) ((ok? (car l)) (cons (car l) (filter ok? (cdr l)))) (else (filter ok? (cdr l)))))
(define (%syntax-rules spec)
  (let* ((ell (if (symbol? (car spec)) (car spec) '...))
         (spec (if (symbol? (car spec)) (cdr spec) spec))
         (lits (car spec)) (rules (cdr spec)))
    (%macro (lambda (form)
              (let loop ((rs rules))
                (if (null? rs) (error "no syntax-rules pattern matches" form)
                    (let ((b (%sr-match (cdar (car rs)) (cdr form) lits ell (list (cons '%ok #t)))))
                      (if b (%sr-expand (cadr (car rs)) b ell) (loop (cdr rs))))))))))

; dynamic-wind (escape-only continuations: unwinding runs the after thunks; there is no re-entry)
(define *winders* '())
(define (dynamic-wind before thunk after)
  (before)
  (set! *winders* (cons (cons before after) *winders*))
  (let ((v (thunk))) (set! *winders* (cdr *winders*)) (after) v))
(define (%unwind-to saved)
  (let loop () (if (and (pair? *winders*) (not (eq? *winders* saved)))
                   (let ((w (car *winders*))) (set! *winders* (cdr *winders*)) ((cdr w)) (loop)))))
(define (values . xs) (if (and (pair? xs) (null? (cdr xs))) (car xs) (%make-record '%values xs)))
(define (%values? v) (and (%record? v) (eq? (%record-type v) '%values)))
(define (call-with-values producer consumer)
  (let ((v (producer))) (if (%values? v) (apply consumer (%record-ref v 0)) (consumer v))))
(define (call-with-current-continuation f)
  (let ((saved *winders*))
    (%callcc (lambda (k) (f (lambda vals (%unwind-to saved) (k (apply values vals))))))))
(define call/cc call-with-current-continuation)

; exceptions
(define *handlers* '())
(define (%make-error msg irritants) (%make-record '%error-object msg irritants))
(define (error-object? x) (and (%record? x) (eq? (%record-type x) '%error-object)))
(define (error-object-message e) (%record-ref e 0))
(define (error-object-irritants e) (%record-ref e 1))
(define (read-error? x) #f)
(define (file-error? x) #f)
(define (%uncaught obj)
  (if (error-object? obj)
      (begin (display (error-object-message obj))
             (for-each (lambda (i) (display " ") (write i)) (error-object-irritants obj)))
      (begin (display "uncaught exception: ") (write obj)))
  (newline) (%repl-reset))
(define (%with-handlers hs thunk)
  (let ((old *handlers*)) (dynamic-wind (lambda () (set! *handlers* hs)) thunk (lambda () (set! *handlers* old)))))
(define (with-exception-handler h thunk) (%with-handlers (cons h *handlers*) thunk))
(define (raise-continuable obj)
  (if (null? *handlers*) (%uncaught obj)
      (let ((h (car *handlers*))) (%with-handlers (cdr *handlers*) (lambda () (h obj))))))
(define (raise obj)
  (raise-continuable obj)
  (%uncaught (%make-error "handler returned from raise" (list obj))))
(define (error msg . irritants) (raise (%make-error msg irritants)))
(define (%guard handler thunk)
  ((call/cc (lambda (k)
              (with-exception-handler (lambda (c) (k (lambda () (handler c))))
                                      (lambda () (let ((v (thunk))) (lambda () v))))))))
(define-syntax guard
  (%macro (lambda (f)
            (let ((var (car (cadr f))) (clauses (cdr (cadr f))))
              (list '%guard
                    (list 'lambda (list var) (cons 'cond (append clauses (list (list 'else (list 'raise-continuable var))))))
                    (cons 'lambda (cons '() (cddr f))))))))

; promises
(define (%make-promise done v) (%make-record '%promise (list done v)))
(define (promise? x) (and (%record? x) (eq? (%record-type x) '%promise)))
(define (make-promise v) (if (promise? v) v (%make-promise #t v)))
(define (force p)
  (if (not (promise? p)) p
      (let ((s (%record-ref p 0)))
        (if (car s) (cadr s)
            (let* ((v ((cadr s))) (s2 (%record-ref p 0)))
              (cond ((car s2) (cadr s2))
                    ((promise? v) (%record-set! p 0 (%record-ref v 0)) (force p))
                    (else (%record-set! p 0 (list #t v)) v)))))))
(define-syntax delay (%macro (lambda (f) (list '%make-promise #f (list 'lambda '() (list '%make-promise #t (cadr f)))))))
(define-syntax delay-force (%macro (lambda (f) (list '%make-promise #f (list 'lambda '() (cadr f))))))

; parameters
(define (make-parameter v . conv)
  (let* ((c (if (pair? conv) (car conv) (lambda (x) x))) (cell (list (c v))))
    (lambda args (cond ((null? args) (car cell)) ((eq? (car args) '%set) (set-car! cell (cadr args))) (else c)))))
(define (%parameterize ps vs thunk)
  (let ((new (map (lambda (p v) ((p '%conv) v)) ps vs)) (old (map (lambda (p) (p)) ps)))
    (dynamic-wind (lambda () (for-each (lambda (p v) (p '%set v)) ps new)) thunk
                  (lambda () (for-each (lambda (p v) (p '%set v)) ps old)))))
(define-syntax parameterize
  (%macro (lambda (f) (list '%parameterize (cons 'list (map car (cadr f))) (cons 'list (map cadr (cadr f)))
                            (cons 'lambda (cons '() (cddr f)))))))

; multiple-value binding forms (let-values binds left to right, like let*-values)
(define (%lv bindings body)
  (if (null? bindings) (cons 'let (cons '() body))
      (list 'call-with-values (list 'lambda '() (cadr (car bindings)))
            (list 'lambda (car (car bindings)) (%lv (cdr bindings) body)))))
(define-syntax let-values (%macro (lambda (f) (%lv (cadr f) (cddr f)))))
(define-syntax let*-values (%macro (lambda (f) (%lv (cadr f) (cddr f)))))
(define-syntax define-values
  (%macro (lambda (f)
            (let ((vars (cadr f)) (tmps (map (lambda (v) (string->symbol (string-append "%t-" (symbol->string v)))) (cadr f))))
              (cons 'begin (append (map (lambda (v) (list 'define v #f)) vars)
                                   (list (list 'call-with-values (list 'lambda '() (caddr f))
                                               (cons 'lambda (cons tmps (map (lambda (v t) (list 'set! v t)) vars tmps))))
                                         '(if #f #f))))))))
(define (floor/ n d) (let ((q (floor (/ n d)))) (values q (- n (* d q)))))
(define (truncate/ n d) (values (quotient n d) (remainder n d)))
(define (floor-quotient n d) (floor (/ n d)))
(define (floor-remainder n d) (modulo n d))
(define (truncate-quotient n d) (quotient n d))
(define (truncate-remainder n d) (remainder n d))
(define (exact-integer-sqrt n) (let ((s (%isqrt n))) (values s (- n (* s s)))))

; records
(define-syntax define-record-type
  (%macro (lambda (f)
            (let* ((type (cadr f)) (ctor (caddr f)) (pred (cadddr f)) (fields (cddddr f)) (names (map car fields))
                   (idx (lambda (n) (let loop ((l names) (i 0)) (if (eq? (car l) n) i (loop (cdr l) (+ i 1)))))))
              (cons 'begin
                    (append (list (list 'define type (list 'quote type)))
                            (if (pair? ctor)
                                (list (list 'define (car ctor)
                                            (list 'lambda (cdr ctor)
                                                  (cons '%make-record (cons (list 'quote type) (map (lambda (n) (if (memq n (cdr ctor)) n #f)) names))))))
                                '())
                            (list (list 'define pred (list 'lambda '(x) (list 'and '(%record? x) (list 'eq? '(%record-type x) (list 'quote type))))))
                            (apply append
                                   (map (lambda (fd)
                                          (let ((i (idx (car fd))))
                                            (cons (list 'define (cadr fd) (list 'lambda '(r) (list '%record-ref 'r i)))
                                                  (if (pair? (cddr fd)) (list (list 'define (caddr fd) (list 'lambda '(r v) (list '%record-set! 'r i 'v)))) '()))))
                                        fields))
                            (list (list 'quote type))))))))

; case-lambda
(define (%arity formals) (let loop ((f formals) (n 0)) (cond ((null? f) n) ((pair? f) (loop (cdr f) (+ n 1))) (else (- -1 n)))))
(define (%case-lambda clauses)
  (lambda args
    (let ((n (length args)))
      (let loop ((cs clauses))
        (cond ((null? cs) (error "no case-lambda clause matches" n))
              ((let ((a (caar cs))) (if (< a 0) (>= n (- -1 a)) (= n a))) (apply (cdar cs) args))
              (else (loop (cdr cs))))))))
(define-syntax case-lambda
  (%macro (lambda (f) (list '%case-lambda (cons 'list (map (lambda (c) (list 'cons (list 'quote (%arity (car c))) (cons 'lambda c))) (cdr f)))))))

; ---- item 6: primitives check their argument count: (name min max), max 255 = any ----
(for-each (lambda (a) (%arity! (car a) (cadr a) (caddr a)))
  '((+ 0 255) (- 1 255) (* 0 255) (/ 1 255) (quotient 2 2) (remainder 2 2) (modulo 2 2)
    (= 1 255) (< 1 255) (> 1 255) (<= 1 255) (>= 1 255) (eq? 2 2) (eqv? 2 2)
    (car 1 1) (cdr 1 1) (cons 2 2) (null? 1 1) (pair? 1 1) (symbol? 1 1) (procedure? 1 1) (boolean? 1 1)
    (exact 1 1) (inexact 1 1) (number? 1 1) (real? 1 1) (complex? 1 1) (integer? 1 1) (rational? 1 1)
    (exact? 1 1) (inexact? 1 1) (exact-integer? 1 1) (%numerator 1 1) (%denominator 1 1)
    (nan? 1 1) (infinite? 1 1) (%ftruncate 1 1) (%fsqrt 1 1)
    (apply 2 255) (display 1 2) (write 1 2) (newline 0 1)
    (string? 1 1) (vector? 1 1) (bytevector? 1 1) (char? 1 1) (char->integer 1 1) (integer->char 1 1)
    (string-length 1 1) (vector-length 1 1) (bytevector-length 1 1)
    (string-ref 2 2) (string-set! 3 3) (vector-ref 2 2) (vector-set! 3 3)
    (bytevector-u8-ref 2 2) (bytevector-u8-set! 3 3) (make-string 1 2) (make-vector 1 2) (make-bytevector 1 2)
    (%string->list 3 3) (%vector->list 3 3) (%bytevector->list 1 1)
    (list->string 1 1) (list->vector 1 1) (list->bytevector 1 1)
    (%substring 3 3) (%string-append2 2 2) (%string-compare 2 2) (string->symbol 1 1) (symbol->string 1 1)
    (set-car! 2 2) (set-cdr! 2 2) (%macro 1 1) (%callcc 1 1) (%make-record 1 255) (%record? 1 1)
    (%record-type 1 1) (%record-ref 2 2) (%record-set! 3 3) (%arity! 3 3)))
