; prelude.scm -- R7RS-small procedures written in the chip Scheme itself.
; host.lisp sends this file to the chip REPL one line at a time: keep one form per line.
(define (not x) (if x #f #t))
(define (caar x) (car (car x)))
(define (cadr x) (car (cdr x)))
(define (cdar x) (cdr (car x)))
(define (cddr x) (cdr (cdr x)))
(define (caddr x) (car (cddr x)))
(define (list . xs) xs)
(define (length l) (let loop ((l l) (n 0)) (if (pair? l) (loop (cdr l) (+ n 1)) n)))
(define (reverse l) (let loop ((l l) (acc '())) (if (pair? l) (loop (cdr l) (cons (car l) acc)) acc)))
(define (append2 a b) (if (pair? a) (cons (car a) (append2 (cdr a) b)) b))
(define (append . ls) (cond ((null? ls) '()) ((null? (cdr ls)) (car ls)) (else (append2 (car ls) (apply append (cdr ls))))))
(define (list-tail l k) (if (= k 0) l (list-tail (cdr l) (- k 1))))
(define (list-ref l k) (car (list-tail l k)))
(define (map1 f l) (if (pair? l) (cons (f (car l)) (map1 f (cdr l))) '()))
(define (any-null? ls) (cond ((null? ls) #f) ((null? (car ls)) #t) (else (any-null? (cdr ls)))))
(define (map f . ls) (if (null? (cdr ls)) (map1 f (car ls)) (if (any-null? ls) '() (cons (apply f (map1 car ls)) (apply map f (map1 cdr ls))))))
(define (for-each f . ls) (if (any-null? ls) #t (begin (apply f (map1 car ls)) (apply for-each f (map1 cdr ls)))))
(define (equal? a b) (cond ((and (pair? a) (pair? b)) (and (equal? (car a) (car b)) (equal? (cdr a) (cdr b)))) ((and (string? a) (string? b)) (= 0 (%string-compare a b))) ((and (vector? a) (vector? b)) (equal? (vector->list a) (vector->list b))) ((and (bytevector? a) (bytevector? b)) (equal? (%bytevector->list a) (%bytevector->list b))) (else (eqv? a b))))
(define (mem= same? x l) (cond ((null? l) #f) ((same? x (car l)) l) (else (mem= same? x (cdr l)))))
(define (memq x l) (mem= eq? x l))
(define (memv x l) (mem= eqv? x l))
(define (member x l) (mem= equal? x l))
(define (ass= same? x l) (cond ((null? l) #f) ((same? x (car (car l))) (car l)) (else (ass= same? x (cdr l)))))
(define (assq x l) (ass= eq? x l))
(define (assv x l) (ass= eqv? x l))
(define (assoc x l) (ass= equal? x l))
(define (zero? n) (= n 0))
(define (positive? n) (> n 0))
(define (negative? n) (< n 0))
(define (odd? n) (not (= 0 (remainder n 2))))
(define (even? n) (= 0 (remainder n 2)))
(define (abs n) (if (< n 0) (- n) n))
(define (max x . r) (let loop ((m x) (r r) (i (inexact? x))) (if (null? r) (if i (inexact m) m) (loop (if (> (car r) m) (car r) m) (cdr r) (or i (inexact? (car r)))))))
(define (min x . r) (let loop ((m x) (r r) (i (inexact? x))) (if (null? r) (if i (inexact m) m) (loop (if (< (car r) m) (car r) m) (cdr r) (or i (inexact? (car r)))))))
(define (numerator q) (if (exact? q) (%numerator q) (inexact (%numerator (exact q)))))
(define (denominator q) (if (exact? q) (%denominator q) (inexact (%denominator (exact q)))))
(define (exact->inexact z) (inexact z))
(define (inexact->exact z) (exact z))
(define (finite? z) (not (or (nan? z) (infinite? z))))
(define (gcd . ns) (if (null? ns) 0 (let loop ((a (abs (car ns))) (r (cdr ns))) (if (null? r) a (loop (let g ((a a) (b (abs (car r)))) (if (= b 0) a (g b (remainder a b)))) (cdr r))))))
(define (lcm . ns) (if (null? ns) 1 (let loop ((a (abs (car ns))) (r (cdr ns))) (if (null? r) a (loop (if (= a 0) 0 (quotient (abs (* a (car r))) (gcd a (car r)))) (cdr r))))))
(define (square n) (* n n))
(define (boolean=? a b) (eq? a b))
(define (symbol=? a b) (eq? a b))
(define (list? l) (let loop ((slow l) (fast l)) (cond ((null? fast) #t) ((not (pair? fast)) #f) ((null? (cdr fast)) #t) ((not (pair? (cdr fast))) #f) (else (let ((fast (cddr fast)) (slow (cdr slow))) (if (eq? fast slow) #f (loop slow fast)))))))
(define (list-copy l) (if (pair? l) (cons (car l) (list-copy (cdr l))) l))
(define (make-list k . fill) (let loop ((k k) (acc '())) (if (= k 0) acc (loop (- k 1) (cons (if (null? fill) #f (car fill)) acc)))))
(define (string->list s . r) (%string->list s (if (pair? r) (car r) 0) (if (and (pair? r) (pair? (cdr r))) (cadr r) (string-length s))))
(define (vector->list v . r) (%vector->list v (if (pair? r) (car r) 0) (if (and (pair? r) (pair? (cdr r))) (cadr r) (vector-length v))))
(define (substring s start end) (%substring s start end))
(define (string-copy s . r) (%substring s (if (pair? r) (car r) 0) (if (and (pair? r) (pair? (cdr r))) (cadr r) (string-length s))))
(define (string-append . ss) (let loop ((acc "") (ss ss)) (if (null? ss) acc (loop (%string-append2 acc (car ss)) (cdr ss)))))
(define (string . cs) (list->string cs))
(define (%chain cmp ok? xs) (let loop ((xs xs)) (cond ((null? (cdr xs)) #t) ((ok? (cmp (car xs) (cadr xs))) (loop (cdr xs))) (else #f))))
(define (string=? . ss) (%chain %string-compare zero? ss))
(define (string<? . ss) (%chain %string-compare negative? ss))
(define (string>? . ss) (%chain %string-compare positive? ss))
(define (string<=? . ss) (%chain %string-compare (lambda (n) (<= n 0)) ss))
(define (string>=? . ss) (%chain %string-compare (lambda (n) (>= n 0)) ss))
(define (%ccmp a b) (- (char->integer a) (char->integer b)))
(define (char=? . cs) (%chain %ccmp zero? cs))
(define (char<? . cs) (%chain %ccmp negative? cs))
(define (char>? . cs) (%chain %ccmp positive? cs))
(define (char<=? . cs) (%chain %ccmp (lambda (n) (<= n 0)) cs))
(define (char>=? . cs) (%chain %ccmp (lambda (n) (>= n 0)) cs))
(define (char-upper-case? c) (let ((n (char->integer c))) (and (>= n 65) (<= n 90))))
(define (char-lower-case? c) (let ((n (char->integer c))) (and (>= n 97) (<= n 122))))
(define (char-alphabetic? c) (or (char-upper-case? c) (char-lower-case? c)))
(define (char-numeric? c) (let ((n (char->integer c))) (and (>= n 48) (<= n 57))))
(define (char-whitespace? c) (if (memv (char->integer c) '(32 9 10 12 13)) #t #f))
(define (char-upcase c) (if (char-lower-case? c) (integer->char (- (char->integer c) 32)) c))
(define (char-downcase c) (if (char-upper-case? c) (integer->char (+ (char->integer c) 32)) c))
(define (char-foldcase c) (char-downcase c))
(define (digit-value c) (if (char-numeric? c) (- (char->integer c) 48) #f))
(define (vector . xs) (list->vector xs))
(define (vector-fill! v x . r) (let loop ((i (if (pair? r) (car r) 0))) (if (< i (if (and (pair? r) (pair? (cdr r))) (cadr r) (vector-length v))) (begin (vector-set! v i x) (loop (+ i 1))))))
(define (vector-copy v . r) (list->vector (apply vector->list v r)))
(define (vector-append . vs) (list->vector (apply append (map vector->list vs))))
(define (vector-map f . vs) (list->vector (apply map f (map vector->list vs))))
(define (vector-for-each f . vs) (apply for-each f (map vector->list vs)))
(define (string-map f . ss) (list->string (apply map f (map string->list ss))))
(define (string-for-each f . ss) (apply for-each f (map string->list ss)))
(define (vector->string v . r) (list->string (apply vector->list v r)))
(define (string->vector s . r) (list->vector (apply string->list s r)))
(define (bytevector . bs) (list->bytevector bs))
(define (bytevector->list b) (%bytevector->list b))
(define (bytevector-copy b . r) (let ((l (%bytevector->list b))) (list->bytevector (list-head (list-tail l (if (pair? r) (car r) 0)) (- (if (and (pair? r) (pair? (cdr r))) (cadr r) (length l)) (if (pair? r) (car r) 0))))))
(define (list-head l k) (if (= k 0) '() (cons (car l) (list-head (cdr l) (- k 1)))))
(define (bytevector-append . bs) (list->bytevector (apply append (map %bytevector->list bs))))
(define (utf8->string b) (list->string (map integer->char (%bytevector->list b))))
(define (string->utf8 s) (list->bytevector (map char->integer (string->list s))))
(define (floor x) (cond ((exact-integer? x) x) ((exact? x) (let ((n (numerator x)) (d (denominator x))) (if (>= n 0) (quotient n d) (- (quotient (+ (- n) d -1) d))))) (else (let ((t (%ftruncate x))) (if (> t x) (- t 1) t)))))
(define (ceiling x) (- (floor (- x))))
(define (truncate x) (cond ((exact-integer? x) x) ((exact? x) (quotient (numerator x) (denominator x))) (else (%ftruncate x))))
(define (round x) (let* ((f (floor x)) (diff (- x f))) (cond ((< diff 1/2) f) ((> diff 1/2) (+ f 1)) ((even? (exact f)) f) (else (+ f 1)))))
(define (%isqrt n) (if (< n 2) n (let loop ((x n)) (let ((y (quotient (+ x (quotient n x)) 2))) (if (>= y x) x (loop y))))))
(define (sqrt x) (cond ((and (exact-integer? x) (>= x 0)) (let ((s (%isqrt x))) (if (= (* s s) x) s (%fsqrt x)))) ((and (exact? x) (>= x 0)) (let ((a (sqrt (numerator x))) (b (sqrt (denominator x)))) (if (and (exact? a) (exact? b)) (/ a b) (%fsqrt x)))) (else (%fsqrt x))))
(define (exact-integer-sqrt n) (let ((s (%isqrt n))) (list s (- n (* s s)))))
(define (%cicmp a b) (- (char->integer (char-foldcase a)) (char->integer (char-foldcase b))))
(define (char-ci=? . cs) (%chain %cicmp zero? cs))
(define (char-ci<? . cs) (%chain %cicmp negative? cs))
(define (char-ci>? . cs) (%chain %cicmp positive? cs))
(define (char-ci<=? . cs) (%chain %cicmp (lambda (n) (<= n 0)) cs))
(define (char-ci>=? . cs) (%chain %cicmp (lambda (n) (>= n 0)) cs))